// Angular/Projects/GlobalMart/global-mart-fe/src/app/wishlist/wishlist.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-wishlist',
  templateUrl: './wishlist.component.html',
  styleUrls: ['./wishlist.component.css']
})
export class WishlistComponent {
  allWishListItems:any = []
}

<div>
    <div *ngIf="allWishListItems.length === 0" class="d-flex justify-content-center align-items-center flex-column">
        <img src="https://cdn-icons-png.flaticon.com/512/11329/11329060.png" alt="">
        <h3 class="text-danger">Your wishlist is empty</h3>
        <button class="btn text-success" routerLink="" style="font-weight: 800; text-decoration: underline;">Add items to your wishlist</button>
    </div>
    <div class="container px-4 mt-4">
        <h3 class="text-danger text-center">Your wishlist items</h3>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="col mb-5" >
                <div class="card h-100 p-3">
                    <!-- Product image-->
                    <img class="card-img-top" src="" alt="..." height="250px" 
                    />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Product name</h5>
                            <!-- Product price-->
                            <!-- {{item.price|currency:'USD'}} -->
                             price
                        </div>
                    </div>
                    <!-- Product actions-->
                   <div class="d-flex justify-content-between">
                        <a class="btn btn-outline-danger" ><i class="fa fa-solid fa-trash"></i></a>
                        <a class="btn btn-outline-success"><i class="fa fa-solid fa-cart-shopping"></i></a>
                   </div>
                </div>
            </div>
        </div>

    </div>
</div>

// React/Projects/redux/ekart/src/pages/Wishlist.jsx
import React from "react";
import { useDispatch, useSelector } from "react-redux";
import { Row, Col, Card, Button } from "react-bootstrap";
import { Link } from "react-router-dom";
import { removeItem } from "../redux/wishlistSlice";
import { addToCart } from "../redux/cartSlice";


function Wishlist() {
  const wishListItem = useSelector((state) => state.wishlistReducer);
  // console.log("===============Wishlist Items in wishlist Page =================");
  // console.log(wishListItem);
  const dispatch = useDispatch();
  const handleWishListItem = (item)=>{
    dispatch(addToCart(item));
    dispatch(removeItem(item.id));
  }
  return (
    <>
      <button className="btn btn-light mt-4 ms-4">
        <Link to="/" style={{ textDecoration: "none", color: "black" }}>
          <i className="fa-solid fa-arrow-left me-2"></i>BACK TO HOME
        </Link>
      </button>
      <Row className="m-5 w-100">
        {wishListItem?.length > 0 ? (
          wishListItem.map((item) => (
            <Col className="m-2" sm={12} md={6} lg={4} xl={3}>
              <Card style={{ width: "18rem", height: "33rem" }}>
                <Card.Img
                  variant="top"
                  src={item.image}
                  style={{ height: "300px" }}
                  className="p-2"
                />
                <Card.Body>
                  <Card.Title>{item.title.slice(0, 20)}...</Card.Title>
                  <Card.Text>
                    <p>{item.description.slice(0, 80)}...</p>
                    <p className="fw-bolder text-center">
                      Price : ${item.price}
                    </p>
                  </Card.Text>
                  <div className="d-flex align-items-center justify-content-between">
                    <Button
                      variant="outline-danger"
                      onClick={() => dispatch(removeItem(item.id))}
                    >
                      <i class="fa-solid fa-trash"></i>
                    </Button>
                    <Button variant="outline-success" onClick={()=>handleWishListItem(item)}>
                      <i class="fa-solid fa-cart-shopping"></i>
                    </Button>
                  </div>
                </Card.Body>
              </Card>
            </Col>
          ))
        ) : (
          <div style={{height:"100vh"}} className="d-flex align-items-center flex-column">
            <img src="https://mir-s3-cdn-cf.behance.net/projects/404/54b13147340145.Y3JvcCw0MDUsMzE3LDAsNDI.png"></img>
          </div>
        )}
      </Row>
    </>
  );
}

export default Wishlist;
