// Angular/user-portal-project/user-portal-miniproject/src/app/header/header.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {

  constructor(private router: Router) { }
  logout(){
    this.router.navigateByUrl("");
  }
}

<nav class="navbar p-3" style="background-color: aqua;">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="assets/users-icon.svg" class="me-3"/>
        EMPLOYEE PORTAL
      </a>
      <button class="btn" (click)="logout()">
        <img src="assets/power--icon.svg"/>
      </button>
    </div>
  </nav>

// MERN/projects/project-fair-front-end/src/components/Header.jsx
import React from "react";
import Container from "react-bootstrap/Container";
import Navbar from "react-bootstrap/Navbar";
import logo from "/projectfairlogo.svg"
import {Link} from "react-router-dom"
import logout from "/logout-icon.svg"
function Header() {
  return (
    <>
      <Navbar className="bg-primary">
        <Container>
          
          <Navbar.Brand href="#home">
          <Link to="/" style={{textDecoration:"none", color:"white"}}>
            <img
              alt=""
              src={logo}
              width="30"
              height="30"
              className="d-inline-block align-top"
            />{" "}
            Project Fair</Link>
          </Navbar.Brand>
          <button className="btn btn-warning"><img src={logout}/>{" "}Logout</button>
        </Container>
      </Navbar>
    </>
  );
}

export default Header;
