// React/Projects/redux/ekart/src/pages/Cart.jsx
import React from "react";
import { useDispatch, useSelector } from "react-redux";
import { removeFromCart } from "../redux/cartSlice";

function Cart() {
  const dispatch = useDispatch();
  const cart = useSelector((state) => state.cartReducer);
  // console.log(cart);
  return (
    <>
      {cart?.length > 0 ? (
        <div style={{ marginTop: "8rem" }}>
          <div className="row w-100">
            <div className="col lg-6 m-5">
              <table className="table shadow border">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Product Title</th>
                    <th>Image</th>
                    <th>Price</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {cart?.map((item, index) => (
                    <tr>
                      <td>{index + 1}</td>
                      <td>{item?.title?.slice(0, 20)}</td>
                      <td>
                        <img
                          src={item.image}
                          style={{ width: "5rem", height: "5rem" }}
                        />
                      </td>
                      <td>${item.price}</td>
                      <td>
                        <button
                          className="btn btn-danger"
                          onClick={() => dispatch(removeFromCart(item.id))}
                        >
                          <i className="fa-solid fa-trash"></i>
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div className="col-lg-4">
              <div className="border shadow p-5 mt-5">
                <h3 className="text-primary">Order Summary</h3>
                <h5>
                  Total no:products :{" "}
                  <span className="text-warning">{cart?.length}</span>
                </h5>
                <h5>
                  Total Price :{" "}
                  <span className="text-warning">
                    $
                    {cart
                      ?.reduce(
                        (totalPrice, currentValue) =>
                          totalPrice + currentValue.price,
                        0
                      )
                      ?.toFixed(2)}
                  </span>
                </h5>
                <button className="btn btn-success rounded w-100">
                  CHECKOUT
                </button>
              </div>
            </div>
          </div>
          {/* <div className="display-5 d-flex justify-content-center me-5 mt-0">
            <p>
              Total:$
              {cart
                ?.reduce(
                  (accumulator, currentValue) =>
                    accumulator + currentValue.price,
                  0
                )
                ?.toFixed(2)}
            </p>
          </div> */}
        </div>
      ) : (
        <div
          style={{ height: "70vh" }}
          className="d-flex align-items-center flex-column"
        >
          <img src="https://mir-s3-cdn-cf.behance.net/projects/404/54b13147340145.Y3JvcCw0MDUsMzE3LDAsNDI.png" />
          <p>Your cart is empty!</p>
        </div>
      )}
    </>
  );
}

export default Cart;

// Angular/Projects/GlobalMart/global-mart-fe/src/app/cart/cart.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent {
  allCartItems :any = [];
}

<div>
    <div *ngIf="allCartItems.length === 0" class="d-flex justify-content-center align-items-center flex-column">
        <img src="https://cdn-icons-png.flaticon.com/512/11329/11329060.png" alt="">
        <h3 class="text-danger">Your cart is empty</h3>
        <button class="btn text-success" routerLink="" style="font-weight: 800; text-decoration: underline;">Add items to your cart</button>
    </div>
    <div class="container-fluid p-3 mt-3">
        <h3 class="text-danger text-center">Cart Summary</h3>
        <div class="row w-100">
            <div class="col-md-1"></div>
            <div class="col-md-7">
                <table class="table shadow mt-4 border rounded">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Product Name</th>
                            <th>Image</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>TShirt</td>
                            <td><img src="https://cdn.pixabay.com/photo/2016/12/06/09/31/blank-1886008_640.png" alt="" style="width: 4rem; height: 4rem;"/></td>
                            <td>
                                <div class="d-flex">
                                    <button class="btn fw-bolder fs-4">-</button>
                                    <input type="number" class="form-control text-center" style="max-width: 4rem;">
                                    <button class="btn fw-bolder fs-4">+</button>
                                </div>
                            </td>
                            <td>25</td>
                            <td>
                                <button class="btn btn-outline-danger"><i class="fa-solid fa-trash"></i></button>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="d-flex justify-content-center">
                    <button class="btn btn-outline-danger">EMPTY CART</button>
                    <button class="btn btn-outline-success ms-3" routerLink="/">ADD MORE</button>
                </div>
            </div>
            <div class="col-md-3">
                <div class="border shadow rounded p-4 mt-4">
                    <h3>Grand Total : <span class="text-primary">1045</span></h3>
                    <button class="btn btn-success">CHECKOUT</button>
                </div>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
</div>
